version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: todoapi
      MONGO_INITDB_ROOT_PASSWORD: apicuaresma
      MONGO_DATABASE_NAME: app
    ports:
      - "27025:27017"